# Generated by Django 5.2.2 on 2025-06-07 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='书名')),
                ('pub_date', models.DateField(verbose_name='发布时间')),
                ('readcount', models.IntegerField(default=0, verbose_name='阅读量')),
                ('commentcount', models.IntegerField(default=0, verbose_name='评论量')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '图书',
                'db_table': 'bookinfo',
            },
        ),
        migrations.CreateModel(
            name='Peopleinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='人名')),
                ('gender', models.SmallIntegerField(choices=[(1, 'male'), (2, 'female')], verbose_name='性别')),
                ('description', models.CharField(max_length=10, null=True, verbose_name='描述信息')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.bookinfo', verbose_name='图书')),
            ],
            options={
                'verbose_name': '人物信息',
                'db_table': 'peopleinfo',
            },
        ),
    ]
